### ISSUE TITLE
shef cannot install http|https://* type repository  (v0.5.99)

### ISSUE THREAD

**Issue by shimmortal** [youmeim/shelib#13]
`shef install ` command has several bugs. fix it.

- [ ] `shef install @package` syntax is deprecated. remove it.
- [ ] `shef install https://github.com/okadash/cosh`: this installation process fails with lack of parent directory (e.g. ~/.shef/db/okadash)
- [ ] and `cook` cannot invoke shelib functions installed with the path above

**Comment by shimmortal** [comment]
There are a few maintainer for shelib functions. So, at now, there is no problem to omit user name parent dir from shelib package db (not for `~/.shef/db/okadash/pkg`, but for `~/.shef/db/pkg`). 
Name duplication for any packages can be ignored for this project, maybe.

**Comment by shimmortal** [comment]
So `shef install https://github.com/okadash/pkg` MAY result the placement of package into `~/.shef/db/pkg`.
That's a solution

**Comment by okadash** [comment]
shelib v0.7+ may support @user/pkg type directory structures, but shelib v0.6.x does not have this directory structure for local repo at now.

**Comment by shimmortal** [comment]
Too complex to fix. I try to rewrite it today.

**Comment by g1eng** [comment]
Sorry @ghost, I'm closing your issue which is not activated ever.
