### ISSUE TITLE
Make test case for @core/shef (dev branch) 

### ISSUE THREAD

**Issue by shimmortal** [youmeim/shelib#9]
Now the [shef](https://github.com/okadash/shef) project has been merged into shelib (for shelib-0.6+).
We have no test cases for shef and its builtin functions, write them.

If possible, use [shellspec](https://github.com/shellspec/shellspec) to make specs (and unit tests).

**Comment by shimmortal** [comment]
Now shef is TOO complex to fix.  I'm rewriting it for v0.6.x.
(New test suite can be used to implement it.)

**Comment by g1eng** [comment]
not needed now
